---
title: MDR Intertidal
author: by Kalimari
output: github_document
---

## Summary

Our overall research question is "How has the ecology of the Mount Desert Rock intertidal zone changed over time?". Mount Desert Rock (MDR) is a 1.2-hectare island 40 km offshore in Maine, with a field station maintained by College of the Atlantic; the intertidal zone of MDR is rocky and high-energy. We used abundant species such as periwinkle snails to measure changes in the intertidal community, and we looked at changes in seaweed cover over time. We also used air and water temperature for the duration of the dataset, which may help explain trends in species abundance.

Periwinkles are of particular interest for two reasons: 1. They are abundant, and therefore counts are more statistically robust than for uncommon species, and 2. There are striking differences between MDR and MDI in the populations of three species: Littorina littorea (common periwinkle), L. obtusata (smooth periwinkle), and L. saxatilis (rough periwinkle). On MDI, L. littorea is dominant and L. saxatilis is rare, but on MDR, L. littorea is rare, and L. saxatilis and L. obtusata (both native species) are abundant. These findings may be due to differences in dispersal methods, as suggested by a similar study on a remote island near Scotland (Johannesson, 1988). Littorina obtusata and L. saxatilis have direct development, so most of their young will stay on MDR. Littorina littorea, however, produces planktonic larvae, which means most young will be carried by ocean currents to other shores. There is evidently enough recruitment to maintain a small population, but not enough for L. littorea to dominate the way it does on MDI. The dataset we are using will allow us to examine changes in the abundances of these three periwinkle species over the past 5-7 years.

We used intertidal data from the Northeastern Coastal Station Alliance (NeCSA), a collaboration among several field stations in the Gulf of Maine that developed a standardized protocol for surveying intertidal invertebrates and algae. We specifically be analyzed data collected on Mount Desert Rock. The survey consists of vertical and horizontal transects collected through quadrats in the intertidal zone. The survey is conducted in the same location every year, with the transect grid marked by metal pegs drilled into the rock. The 3 vertical transects measure algae cover by species in a line perpendicular to the water line. For the horizontal transects, there are three lines of ten 1-meter square quadrats, placed every 3 meters at high, medium, and low tide levels parallel to the water line. In each quadrat, macroscopic invertebrates are counted and algae canopy and subcanopy cover is recorded; only species on the standardized NeCSA list are recorded.

For this project we only used the horizontal transects. This data was collected annually from 2017 to 2023. In the early years, the data was collected by high school students who were trained on the rock. The project was continued by Marina in 2022 and 2023. 

All of our graphs were made in the mdrgraphs document (/project/analysis/mdrgraphs.md). 

In our Scatterplot of Mount Desert Rock mid tide temperatures in degrees Celsius. Temperatures are shown across a date range from 2017 to 2022. The temperatures range from negative 10 to positive 30 degrees Celsius and fluctuate throughout the year. Colder temperatures occur in the winter and warmer temperatures occur in the summer months. Temperature is an important factor in the intertidal because it helps determine the distribution of different species. Organisms found in the high intertidal need to be the most adapted to changes in temperature. Water temperatures stay relatively constant, but changes in air temperature can greatly impact the interidal. Some species, like crabs, will migrate into the lower intertidal and subtitle regions during the winter to avoid colder temperatures. And, on the west coast a few years ago, there was a heat dome that killed off many intertidal organisms who were exposed to heat for too long. However, we found that there was not a great enough variation of temperature over the years to change the species composition.

Snail populations are increasing.

The seaweed cover for the species we looked are decreasing.


In terms of limitations, there was a lack of standardization in data collection as it was collected by different people each year. There could have also been some misidentification as the data was collected by students who were only trained a week prior to collection, this led to a baseline of human error. In some cases, the identification did not make sense. For example, Ulva, a low intertidal seaweed species, was listed in the high intertidal. To resolve this, we had to remove all observations of Ulva in the high intertidal. Additionally, some species are really hard to identify, for example, we had to group all the fucuses together since it is almost impossible to tell them apart without DNA identification due to factors like phenotypic plasticity. Another limitation was that there are missing years.Because of unclear data entry, we had to omit all the survey data from 2018. We omitted 2017 in the snail plot, because periwinkle snails were not identified to species. We also weren’t able to get temperature data from 2023.

In the future, it is important to continue monitoring temperature changes to see if this impacts species composition in a changing climate. It would also be helpful to conduct an experiment to see if the herbivorous snails are causing the decline in seaweed. In terms of data analysis, we would like to look at the vertical transects to visualize species composition from the high to low intertidal. Furthermore, it would be interesting to visualize species composition for other invertebrates as we only looked at snails.



```{r load-data, echo = FALSE}
# load data here, if you like
```

## Presentation

Our presentation can be found [here](https://docs.google.com/presentation/d/1hcCbeBnJPDstauCd-XchuDcr6iWFrnO3oZpX9izKzj0/edit?usp=sharing).

## Data 

Include a citation for your data here. 
See http://libraryguides.vu.edu.au/c.php?g=386501&p=4347840 for guidance on proper citation for datasets. 
If you got your data off the web, make sure to note the retrieval date.

NOAA, 2017, National Oceanographic and Atmospheric Administration, https://tidesandcurrents.noaa.gov/waterlevels.html?id=8413320&units=standard&bdate=20170101&edate=20171231&timezone=GMT&datum=MLLW&interval=hl&action=data 

NOAA, 2018, National Oceanographic and Atmospheric Administration, https://tidesandcurrents.noaa.gov/waterlevels.html?id=8413320&units=standard&bdate=20180101&edate=20181231&timezone=GMT&datum=MLLW&interval=hl&action=data

NOAA, 2019, National Oceanographic and Atmospheric Administration, https://tidesandcurrents.noaa.gov/waterlevels.html?id=8413320&units=standard&bdate=20190101&edate=20191231&timezone=GMT&datum=MLLW&interval=hl&action=data

NOAA, 2020, National Oceanographic and Atmospheric Administration, https://tidesandcurrents.noaa.gov/waterlevels.html?id=8413320&units=standard&bdate=20200101&edate=20201231&timezone=GMT&datum=MLLW&interval=hl&action=data

NOAA, 2021, National Oceanographic and Atmospheric Administration, https://tidesandcurrents.noaa.gov/waterlevels.html?id=8413320&units=standard&bdate=20210101&edate=20211231&timezone=GMT&datum=MLLW&interval=hl&action=data

NOAA, 2022, National Oceanographic and Atmospheric Administration, https://tidesandcurrents.noaa.gov/waterlevels.html?id=8413320&units=standard&bdate=20220101&edate=20221231&timezone=GMT&datum=MLLW&interval=hl&action=data

NOAA, 2023, National Oceanographic and Atmospheric Administration, https://tidesandcurrents.noaa.gov/waterlevels.html?id=8413320&units=standard&bdate=20230101&edate=20231231&timezone=GMT&datum=MLLW&interval=hl&action=data
## References

List any references here. You should, at a minimum, list your data source.

Citation: Johannesson, K. (1988). The paradox of Rockall: why is a brooding gastropod (Littorina saxatilis) more widespread than one having a planktonic larval dispersal stage (L. littorea)? Marine Biology, 99(4), 507–513.
