---
title: "Project tidying"
author: "MDR Intertidal"
output: github_document
---

```{r load-packages, message = FALSE}
library(tidyverse)
library(broom)
library(readxl)
```

```{r load-data-2017}

horizontal_MDR_NeCSA_2017  <- read_excel("/cloud/project/data/2017_horizontal_MDR_NeCSA.xlsx", na = c("*all rock", "*skipped because of tide pool"))

```

```{r tidy-seaweed-data-2017}

seaweeds_mdr_2017 <- horizontal_MDR_NeCSA_2017 %>%
  subset(select = -c(Site, Name, Llitt:SembalA2 )) %>%
  add_column(year = "2017") %>%
  rename(date = Date,
         tide_ht = Tide,
         quadrat_m = `Quadrat (m)`,
         Asco_nCC = AscoCC,
         Fucu_vCC = FucVCC,
         Fucu_sCC = FucSCC,
         Fucu_dCC = FucDCC,
         Fucu_spp = FucSpp.CC,
         Asco_nSC = AscoSC,
         Fucu_vSC = FucVSC,
         Fucu_sSC = FucSSC,
         Fucu_dSC = FucDSC,
         Mast_sSC = MstellSC,
         Chon_cSC = ChonCrSC,
         Ulva_iSC = UlvaIntesSC,
         Ulva_lSC = UlvaLacSC,
         Cora_oSC = CorOSC,
         Vert_lSC = VertLanSC,
         Cera_rSC = CerSC,
         Lami_spp = `Laminaria spp.`,
         Porp_sp = `Porphyra sp.`,
         Asco_recruits = AscoR,
         Asco_holdfasts = AscoA,
         Fucu_recruits = FucR,
         Fucu_v_holdfasts = FucVA,
         Fucu_s_holdfasts = FucSA,
         Fucu_d_holdfasts = FucDA,
         Asco_n_ht = `AscoHeight (cm)`,
         Asco_n_bladders = AscoBladders,
         Fucu_spp_holdfasts = FucSppA) %>%
  relocate(year, .after = date) %>%
  fill(c(date, tide_ht), .direction = "down") %>%
  pivot_longer(
    cols = Asco_nCC:Fucu_spp_holdfasts,
    names_to = "seaweed_species",
    values_to = "squares_out_of_25") %>%
  mutate(proportion = `squares_out_of_25`/25) %>%
  filter(!(seaweed_species %in% c("Asco_recruits",
                                  "Asco_holdfasts",
                                  "Fucu_recruits",
                                  "Fucu_v_holdfasts",
                                  "Fucu_s_holdfasts",
                                  "Fucu_d_holdfasts",
                                  "Fucu_spp_holdfasts"
                                  )))

```

```{r tidy-inverts-data-2017}

inverts_mdr_2017 <- horizontal_MDR_NeCSA_2017 %>%
  subset(select = -c(Site,Name, AscoCC:AscoBladders, CarmaeMale, CarmaeFem, CarmaeEgg, HemiMale, HemiFem, HemiEgg, CanirrMale:CanirrEgg, CanborMale:SembalA2)) %>%
  add_column(year = "2017") %>%
  rename(date = Date,
         tide_ht = Tide,
         quadrat_m = `Quadrat (m)`,
         Litt_l = Llitt,
         Litt_o = Liobtu,
         Litt_s = Lsax,
         Litt_spp = `Litt. Spp.`,
         Nuce_l = Nlap,
         Lacu_v = Lacvinc,
         Hiat_a = Hiatarct,
         Ostr_e = Ostredu,
         Myti_e = Myted,
         Modi_m = Modmod,
         Tect_t = Testtest,
         Crep_f = Crepfor,
         Urti_f = Urtfel,
         Metr_s = Metrsen,
         Aste_f = Astfor,
         Aste_v = Astvul,
         Stro_d = Strongdro,
         Lepi_s = Lepsqua,
         Dide_v = Didvex,
         Botr_s = Botrysch,
         Cion_i = Ciointes,
         Gamm_spp = Gamarus,
         Carc_m = CarmaeTot,
         Hemi_s = HemiTot,
         Canc_i = CanirrTot,
         Canc_b = CanborTot) %>%
  pivot_longer(
     cols = Litt_l:Canc_b,
     names_to = "invert_species",
     values_to = "count"
     ) %>%
  relocate(year, .after = date)

```

```{r load-data-2018}

# not sure if this spreadsheet is complete - omit?

# low quadrats

HL00_MDR_NeCSA_2018 <- read_excel("/cloud/project/data/2018_full_NeCSA.xlsx", sheet = "West HT Low", range = "A4:C49") %>%
  mutate(tide_height = "low",
         year = "2018",
         quadrat = 0)

HL03_MDR_NeCSA_2018 <- read_excel("/cloud/project/data/2018_full_NeCSA.xlsx", sheet = "West HT Low", range = "D4:F49") %>%
  mutate(tide_height = "low",
         year = "2018",
         quadrat = 3)

HL06_MDR_NeCSA_2018 <- read_excel("/cloud/project/data/2018_full_NeCSA.xlsx", sheet = "West HT Low", range = "G4:I49") %>%
  mutate(tide_height = "low",
         year = "2018",
         quadrat = 6)

HL09_MDR_NeCSA_2018 <- read_excel("/cloud/project/data/2018_full_NeCSA.xlsx", sheet = "West HT Low", range = "J4:L49") %>%
  mutate(tide_height = "low",
         year = "2018",
         quadrat = 9)

HL12_MDR_NeCSA_2018 <- read_excel("/cloud/project/data/2018_full_NeCSA.xlsx", sheet = "West HT Low", range = "M4:O49") %>%
  mutate(tide_height = "low",
         year = "2018",
         quadrat = 12)

HL15_MDR_NeCSA_2018 <- read_excel("/cloud/project/data/2018_full_NeCSA.xlsx", sheet = "West HT Low", range = "P4:R49") %>%
  mutate(tide_height = "low",
         year = "2018",
         quadrat = 15)

HL18_MDR_NeCSA_2018 <- read_excel("/cloud/project/data/2018_full_NeCSA.xlsx", sheet = "West HT Low", range = "S4:U49") %>%
  mutate(tide_height = "low",
         year = "2018",
         quadrat = 18)

HL21_MDR_NeCSA_2018 <- read_excel("/cloud/project/data/2018_full_NeCSA.xlsx", sheet = "West HT Low", range = "V4:X49") %>%
  mutate(tide_height = "low",
         year = "2018",
         quadrat = 21)

HL24_MDR_NeCSA_2018 <- read_excel("/cloud/project/data/2018_full_NeCSA.xlsx", sheet = "West HT Low", range = "Y4:AA49") %>%
  mutate(tide_height = "low",
         year = "2018",
         quadrat = 24)

HL27_MDR_NeCSA_2018 <- read_excel("/cloud/project/data/2018_full_NeCSA.xlsx", sheet = "West HT Low", range = "AB4:AD49") %>%
  mutate(tide_height = "low",
         year = "2018",
         quadrat = 27)

# mid quadrats

HM00_MDR_NeCSA_2018 <- read_excel("/cloud/project/data/2018_full_NeCSA.xlsx", sheet = "West HT Mid", range = "A4:C49") %>%
  mutate(tide_height = "mid",
         year = "2018",
         quadrat = 0)

HM03_MDR_NeCSA_2018 <- read_excel("/cloud/project/data/2018_full_NeCSA.xlsx", sheet = "West HT Mid", range = "D4:F49") %>%
  mutate(tide_height = "mid",
         year = "2018",
         quadrat = 3)

HM06_MDR_NeCSA_2018 <- read_excel("/cloud/project/data/2018_full_NeCSA.xlsx", sheet = "West HT Mid", range = "G4:I49") %>%
  mutate(tide_height = "mid",
         year = "2018",
         quadrat = 6)

HM09_MDR_NeCSA_2018 <- read_excel("/cloud/project/data/2018_full_NeCSA.xlsx", sheet = "West HT Mid", range = "J4:L49") %>%
  mutate(tide_height = "mid",
         year = "2018",
         quadrat = 9)

HM12_MDR_NeCSA_2018 <- read_excel("/cloud/project/data/2018_full_NeCSA.xlsx", sheet = "West HT Mid", range = "M4:O49") %>%
  mutate(tide_height = "mid",
         year = "2018",
         quadrat = 12)

HM15_MDR_NeCSA_2018 <- read_excel("/cloud/project/data/2018_full_NeCSA.xlsx", sheet = "West HT Mid", range = "P4:R49") %>%
  mutate(tide_height = "mid",
         year = "2018",
         quadrat = 15)

HM18_MDR_NeCSA_2018 <- read_excel("/cloud/project/data/2018_full_NeCSA.xlsx", sheet = "West HT Mid", range = "S4:U49") %>%
  mutate(tide_height = "mid",
         year = "2018",
         quadrat = 18)

HM21_MDR_NeCSA_2018 <- read_excel("/cloud/project/data/2018_full_NeCSA.xlsx", sheet = "West HT Mid", range = "V4:X49") %>%
  mutate(tide_height = "mid",
         year = "2018",
         quadrat = 21)

HM24_MDR_NeCSA_2018 <- read_excel("/cloud/project/data/2018_full_NeCSA.xlsx", sheet = "West HT Mid", range = "Y4:AA49") %>%
  mutate(tide_height = "mid",
         year = "2018",
         quadrat = 24)

HM27_MDR_NeCSA_2018 <- read_excel("/cloud/project/data/2018_full_NeCSA.xlsx", sheet = "West HT Mid", range = "AB4:AD49") %>%
  mutate(tide_height = "mid",
         year = "2018",
         quadrat = 27)

# high quadrats

HH00_MDR_NeCSA_2018 <- read_excel("/cloud/project/data/2018_full_NeCSA.xlsx", sheet = "West HT High", range = "A4:C49") %>%
  mutate(tide_height = "high",
         year = "2018",
         quadrat = 0)

HH03_MDR_NeCSA_2018 <- read_excel("/cloud/project/data/2018_full_NeCSA.xlsx", sheet = "West HT High", range = "D4:F49") %>%
  mutate(tide_height = "high",
         year = "2018",
         quadrat = 3)

HH06_MDR_NeCSA_2018 <- read_excel("/cloud/project/data/2018_full_NeCSA.xlsx", sheet = "West HT High", range = "G4:I49") %>%
  mutate(tide_height = "high",
         year = "2018",
         quadrat = 6)

HH09_MDR_NeCSA_2018 <- read_excel("/cloud/project/data/2018_full_NeCSA.xlsx", sheet = "West HT High", range = "J4:L49") %>%
  mutate(tide_height = "high",
         year = "2018",
         quadrat = 9)

HH12_MDR_NeCSA_2018 <- read_excel("/cloud/project/data/2018_full_NeCSA.xlsx", sheet = "West HT High", range = "M4:O49") %>%
  mutate(tide_height = "high",
         year = "2018",
         quadrat = 12)

HH15_MDR_NeCSA_2018 <- read_excel("/cloud/project/data/2018_full_NeCSA.xlsx", sheet = "West HT High", range = "P4:R49") %>%
  mutate(tide_height = "high",
         year = "2018",
         quadrat = 15)

HH18_MDR_NeCSA_2018 <- read_excel("/cloud/project/data/2018_full_NeCSA.xlsx", sheet = "West HT High", range = "S4:U49") %>%
  mutate(tide_height = "high",
         year = "2018",
         quadrat = 18)

HH21_MDR_NeCSA_2018 <- read_excel("/cloud/project/data/2018_full_NeCSA.xlsx", sheet = "West HT High", range = "V4:X49") %>%
  mutate(tide_height = "high",
         year = "2018",
         quadrat = 21)

HH24_MDR_NeCSA_2018 <- read_excel("/cloud/project/data/2018_full_NeCSA.xlsx", sheet = "West HT High", range = "Y4:AA49") %>%
  mutate(tide_height = "high",
         year = "2018",
         quadrat = 24)

HH27_MDR_NeCSA_2018 <- read_excel("/cloud/project/data/2018_full_NeCSA.xlsx", sheet = "West HT High", range = "AB4:AD49") %>%
  mutate(tide_height = "high",
         year = "2018",
         quadrat = 27)

```

```{r load-data-2019}

horizontal_MDR_NeCSA_2019  <- read_excel("/cloud/project/data/2019_horizontal_MDR_NeCSA.xlsx")

```

```{r tidy-seaweed-data-2019}

seaweeds_mdr_2019 <- horizontal_MDR_NeCSA_2019 %>%
  subset(select = -c(Site, Name, Notes, Semi_bCC, Myti_eCC, Semi_bSC, Myti_eSC, Urti_f:Semi_bA2)) %>%
  add_column(year = "2019") %>%
  pivot_longer(
    cols = Asco_nCC:Cera_rSC,
    names_to = "seaweed_species",
    values_to = "squares_out_of_25") %>%
  mutate(proportion = squares_out_of_25/25) %>%
  rename(date = Date,
         tide_ht = TideHt,
         quadrat_number = Quadrat,
         Asco_n_ht = Asco_nHt,
         Asco_n_bladders = Asco_nBladders) %>%
  relocate(year, .after = date) %>%
  mutate(quadrat_m = case_when(quadrat_number == 1 ~ 0,
                               quadrat_number == 2 ~ 3,
                               quadrat_number == 3 ~ 6,
                               quadrat_number == 4 ~ 9,
                               quadrat_number == 5 ~ 12,
                               quadrat_number == 6 ~ 15,
                               quadrat_number == 7 ~ 18,
                               quadrat_number == 8 ~ 21,
                               quadrat_number == 9 ~ 24,
                               quadrat_number == 10 ~ 27),
         .after = quadrat_number)

```

```{r tidy-inverts-data-2019}

inverts_mdr_2019 <- horizontal_MDR_NeCSA_2019 %>%
  subset(select = -c(Site, Name, Notes, Semi_bCC, Myti_eCC, Semi_bSC, Myti_eSC, Asco_nCC:Fucu_dCC, Asco_nSC:Cera_rSC, Asco_nHt, Asco_nBladders, Myti_eMethod)) %>%
  add_column(year = "2019") %>%
  rename(date = Date,
      tide_ht = TideHt,
      quadrat_number = Quadrat,
      Nuce_l = Nuci_l) %>%
   pivot_longer(
     cols = Urti_f:Semi_bA2,
     names_to = "invert_species",
     values_to = "count"
   ) %>%
  relocate(year, .after = date) %>%
  mutate(quadrat_m = case_when(quadrat_number == 1 ~ 0,
                               quadrat_number == 2 ~ 3,
                               quadrat_number == 3 ~ 6,
                               quadrat_number == 4 ~ 9,
                               quadrat_number == 5 ~ 12,
                               quadrat_number == 6 ~ 15,
                               quadrat_number == 7 ~ 18,
                               quadrat_number == 8 ~ 21,
                               quadrat_number == 9 ~ 24,
                               quadrat_number == 10 ~ 27),
         .after = quadrat_number)

```

```{r load-data-2020}

horizontal_MDR_NeCSA_2020  <- read_excel("/cloud/project/data/2020_horizontal_MDR_NeCSA.xlsx")

```

```{r tidy-seaweed-data-2020}

seaweeds_mdr_2020 <- horizontal_MDR_NeCSA_2020 %>%
  subset(select = -c(Site, Name, Notes, Semi_bCC, Myti_eCC, Semi_bSC, Myti_eSC, Urti_f:Notes ))  %>%
  add_column(year = "2020") %>%
  pivot_longer(
    cols = Asco_nCC:Cera_rSC,
    names_to = "seaweed_species",
    values_to = "squares_out_of_25") %>%
  mutate(proportion = squares_out_of_25/25) %>%
  rename(date = Date,
         tide_ht = TideHt,
         quadrat_number = Quadrat,
         Asco_n_ht = Asco_nHt,
         Asco_n_bladders = Asco_nBladders) %>%
  relocate(year, .after = date) %>%
  mutate(quadrat_m = case_when(quadrat_number == 1 ~ 0,
                               quadrat_number == 2 ~ 3,
                               quadrat_number == 3 ~ 6,
                               quadrat_number == 4 ~ 9,
                               quadrat_number == 5 ~ 12,
                               quadrat_number == 6 ~ 15,
                               quadrat_number == 7 ~ 18,
                               quadrat_number == 8 ~ 21,
                               quadrat_number == 9 ~ 24,
                               quadrat_number == 10 ~ 27),
         .after = quadrat_number)

```

```{r tidy-inverts-data-2020}

inverts_mdr_2020 <- horizontal_MDR_NeCSA_2020 %>%
  subset(select = -c(Site, Name, Notes, Semi_bCC, Myti_eCC, Semi_bSC, Myti_eSC, Asco_nCC:Fucu_dCC, Asco_nSC:Cera_rSC, Asco_nHt, Asco_nBladders, Myti_eMethod)) %>%
  add_column(year = "2020") %>%
  rename(date = Date,
      tide_ht = TideHt,
      quadrat_number = Quadrat,
      Nuce_l = Nuci_l) %>%
   pivot_longer(
     cols = Urti_f:Semi_bA2,
     names_to = "invert_species",
     values_to = "count"
   ) %>%
  relocate(year, .after = date) %>%
  mutate(quadrat_m = case_when(quadrat_number == 1 ~ 0,
                               quadrat_number == 2 ~ 3,
                               quadrat_number == 3 ~ 6,
                               quadrat_number == 4 ~ 9,
                               quadrat_number == 5 ~ 12,
                               quadrat_number == 6 ~ 15,
                               quadrat_number == 7 ~ 18,
                               quadrat_number == 8 ~ 21,
                               quadrat_number == 9 ~ 24,
                               quadrat_number == 10 ~ 27),
         .after = quadrat_number)

```

```{r load-data-2021}

horizontal_MDR_NeCSA_2021  <- read_excel("/cloud/project/data/2021_horizontal_MDR_NeCSA.xlsx")

```

```{r tidy-seaweed-data-2021}

seaweeds_mdr_2021 <- horizontal_MDR_NeCSA_2021 %>%
  subset(select = -c(Site, Name, Notes, Semi_bCC, Myti_eCC, Semi_bSC, Myti_eSC, Urti_f:Notes ))  %>%
  add_column(year = "2021") %>%
  pivot_longer(
    cols = Asco_nCC:Cera_rSC,
    names_to = "seaweed_species",
    values_to = "squares_out_of_25") %>%
  mutate(proportion = squares_out_of_25/25) %>%
  rename(date = Date,
         tide_ht = TideHt,
         quadrat_number = Quadrat,
         Asco_n_ht = Asco_nHt,
         Asco_n_bladders = Asco_nBladders) %>%
  relocate(year, .after = date) %>%
  mutate(quadrat_m = case_when(quadrat_number == 1 ~ 0,
                               quadrat_number == 2 ~ 3,
                               quadrat_number == 3 ~ 6,
                               quadrat_number == 4 ~ 9,
                               quadrat_number == 5 ~ 12,
                               quadrat_number == 6 ~ 15,
                               quadrat_number == 7 ~ 18,
                               quadrat_number == 8 ~ 21,
                               quadrat_number == 9 ~ 24,
                               quadrat_number == 10 ~ 27),
         .after = quadrat_number)

```

```{r tidy-inverts-data-2021}

inverts_mdr_2021 <- horizontal_MDR_NeCSA_2021 %>%
  subset(select = -c(Site, Name, Notes, Semi_bCC, Myti_eCC, Semi_bSC, Myti_eSC, Asco_nCC:Fucu_dCC, Asco_nSC:Cera_rSC, Asco_nHt, Asco_nBladders, Myti_eMethod)) %>%
  add_column(year = "2021") %>%
  rename(date = Date,
         tide_ht = TideHt,
         quadrat_number = Quadrat,
         Nuce_l = Nuci_l) %>%
   pivot_longer(cols = Urti_f:Semi_bA2,
                names_to = "invert_species",
                values_to = "count"
                ) %>%
  relocate(year, .after = date) %>%
  mutate(quadrat_m = case_when(quadrat_number == 1 ~ 0,
                               quadrat_number == 2 ~ 3,
                               quadrat_number == 3 ~ 6,
                               quadrat_number == 4 ~ 9,
                               quadrat_number == 5 ~ 12,
                               quadrat_number == 6 ~ 15,
                               quadrat_number == 7 ~ 18,
                               quadrat_number == 8 ~ 21,
                               quadrat_number == 9 ~ 24,
                               quadrat_number == 10 ~ 27),
         .after = quadrat_number)

# need to specify value/NA for quadrat_m if value in quadrat_number doesn't match list?

```

```{r load-data-2022}

horizontal_MDR_NeCSA_2022  <- read_excel("/cloud/project/data/2022_horizontal_MDR_NeCSA.xlsx")

```

```{r tidy-seaweed-data-2022}

seaweeds_mdr_2022 <- horizontal_MDR_NeCSA_2022 %>%
  subset(select = -c(Site, Name, Semi_bCC, Myti_eCC, Semi_bSC, Myti_eSC, Urti_f:Notes)) %>%
  add_column(year = "2022") %>%
  pivot_longer(
    cols = Asco_nCC:Cera_rSC,
    names_to = "seaweed_species",
    values_to = "squares_out_of_25") %>%
  mutate(proportion = squares_out_of_25/25) %>%
  rename(date = Date,
         tide_ht = TideHt,
         quadrat_number = Quadrat) %>%
  relocate(year, .after = date) %>%
  mutate(quadrat_m = case_when(quadrat_number == 1 ~ 0,
                               quadrat_number == 2 ~ 3,
                               quadrat_number == 3 ~ 6,
                               quadrat_number == 4 ~ 9,
                               quadrat_number == 5 ~ 12,
                               quadrat_number == 6 ~ 15,
                               quadrat_number == 7 ~ 18,
                               quadrat_number == 8 ~ 21,
                               quadrat_number == 9 ~ 24,
                               quadrat_number == 10 ~ 27),
         .after = quadrat_number)

```

```{r tidy-inverts-data-2022}
  
inverts_mdr_2022 <- horizontal_MDR_NeCSA_2022 %>%
  subset(select = -c(Site, Name, Semi_bCC, Myti_eCC, Semi_bSC, Myti_eSC, Asco_nCC:Fucu_dCC, Asco_nSC:Cera_rSC, Asco_nHt, Asco_nBladders, Myti_eMethod, Notes)) %>%
  add_column(year = "2022") %>%
  rename(date = Date,
         tide_ht = TideHt,
         quadrat_number = Quadrat,
         Nuce_l = Nuci_l) %>%
  pivot_longer(
    cols = Urti_f:Semi_bA2,
    names_to = "invert_species",
    values_to = "count") %>%
  relocate(year, .after = date) %>%
  mutate(quadrat_m = case_when(quadrat_number == 1 ~ 0,
                               quadrat_number == 2 ~ 3,
                               quadrat_number == 3 ~ 6,
                               quadrat_number == 4 ~ 9,
                               quadrat_number == 5 ~ 12,
                               quadrat_number == 6 ~ 15,
                               quadrat_number == 7 ~ 18,
                               quadrat_number == 8 ~ 21,
                               quadrat_number == 9 ~ 24,
                               quadrat_number == 10 ~ 27),
         .after = quadrat_number)

```

```{r load-data-2023}

horizontal_MDR_NeCSA_2023  <- read_excel("/cloud/project/data/2023_horizontal_MDR_NeCSA.xlsx")

```

```{r tidy-seaweed-data-2023}

seaweeds_mdr_2023 <- horizontal_MDR_NeCSA_2023 %>%
  subset(select = -c(Site, Name, Semi_bCC, Myti_eCC, Semi_bSC, Myti_eSC, Urti_f:Notes)) %>%
  add_column(year = "2023") %>%
  rename(date = Date,
         tide_ht = TideHt,
         quadrat_number = Quadrat) %>%
  pivot_longer(
    cols = Asco_nCC:Cera_rSC,
    names_to = "seaweed_species",
    values_to = "squares_out_of_25") %>%
  mutate(proportion = squares_out_of_25/25) %>%
  relocate(year, .after = date) %>%
  mutate(quadrat_m = case_when(quadrat_number == 1 ~ 0,
                               quadrat_number == 2 ~ 3,
                               quadrat_number == 3 ~ 6,
                               quadrat_number == 4 ~ 9,
                               quadrat_number == 5 ~ 12,
                               quadrat_number == 6 ~ 15,
                               quadrat_number == 7 ~ 18,
                               quadrat_number == 8 ~ 21,
                               quadrat_number == 9 ~ 24,
                               quadrat_number == 10 ~ 27),
         .after = quadrat_number)

```

```{r tidy-inverts-data-2023}
  
inverts_mdr_2023 <- horizontal_MDR_NeCSA_2023 %>%
  subset(select = -c(Site, Name, Semi_bCC, Myti_eCC, Semi_bSC, Myti_eSC, Asco_nCC:Fucu_dCC, Asco_nSC:Cera_rSC, Asco_nHt, Asco_nBladders, Myti_eMethod, Notes)) %>%
  add_column(year = "2023") %>%
  rename(date = Date,
         tide_ht = TideHt,
         quadrat_number = Quadrat,
         Nuce_l = Nuci_l) %>%
  pivot_longer(
    cols = Urti_f:Semi_bA2,
    names_to = "invert_species",
    values_to = "count") %>% 
  relocate(year, .after = date) %>%
  mutate(quadrat_m = case_when(quadrat_number == 1 ~ 0,
                               quadrat_number == 2 ~ 3,
                               quadrat_number == 3 ~ 6,
                               quadrat_number == 4 ~ 9,
                               quadrat_number == 5 ~ 12,
                               quadrat_number == 6 ~ 15,
                               quadrat_number == 7 ~ 18,
                               quadrat_number == 8 ~ 21,
                               quadrat_number == 9 ~ 24,
                               quadrat_number == 10 ~ 27),
         .after = quadrat_number)
  
```

```{r join-everything-seaweed}

# missing 2018

all_seaweeds_mdr <- full_join(seaweeds_mdr_2017, seaweeds_mdr_2019) %>%
  full_join(seaweeds_mdr_2020) %>%
  full_join(seaweeds_mdr_2021) %>%
  full_join(seaweeds_mdr_2022) %>%
  full_join(seaweeds_mdr_2023) %>%
  mutate(tide_ht = as.factor(tide_ht)) %>%
  mutate(tide_ht = fct_relevel(tide_ht, c("H", "M", "L")))

#all_seaweeds_mdr <- all_seaweeds_mdr %>%
  #mutate(seaweed_species = case_when(seaweed_species == "Coro_oSC" ~ "Cora_oSC",))

# ^ how to get it to keep everything else the same?

distinct(all_seaweeds_mdr, seaweed_species) %>%
  arrange(seaweed_species)
  
```

```{r join-everything-inverts}

# missing 2018

all_inverts_mdr <- full_join(inverts_mdr_2017, inverts_mdr_2019) %>%
  full_join(inverts_mdr_2020) %>%
  full_join(inverts_mdr_2021) %>%
  full_join(inverts_mdr_2022) %>%
  full_join(inverts_mdr_2023) %>%
  filter(!(invert_species %in% c("Semi_bA1",
                                 "Semi_bA2",
                                 "Semi_bR1",
                                 "Semi_bR2"))) %>%
  mutate(tide_ht = as.factor(tide_ht)) %>%
  mutate(tide_ht = fct_relevel(tide_ht, c("H", "M", "L")))

glimpse(all_inverts_mdr)

distinct(all_inverts_mdr, invert_species) %>%
  arrange(invert_species)

```

```{r total-snails-per-quadrat-unfaceted}

# total number per quadrat, unfaceted

all_inverts_mdr %>%
  filter(invert_species %in% c("Litt_l",
                               "Litt_o",
                               "Litt_s",
                               "Litt_spp"),
         !(year == 2017)) %>%
  ggplot(mapping = aes(year, count, fill = invert_species)) +
    geom_col(position = "dodge") +
  scale_fill_viridis_d()

```

```{r total-snails-per-quadrat-faceted}

all_inverts_mdr %>%
  filter(invert_species %in% c("Litt_l",
                               "Litt_o",
                               "Litt_s",
                               "Litt_spp"),
         !(year == 2017),
         !is.na(tide_ht)) %>%
  ggplot(mapping = aes(year, count, fill = invert_species)) +
    geom_col(position = "dodge") +
  scale_fill_viridis_d() +
  facet_wrap("tide_ht", nrow = 1)

```

```{r mean-snails-per-quadrat-unfaceted}

# error bars are NOT working (need to get them to line up with their bars)

all_inverts_mdr %>%
  filter(invert_species %in% c("Litt_l",
                               "Litt_o",
                               "Litt_s",
                               "Litt_spp"),
         !(year == 2017),
         !is.na(tide_ht)) %>%
  mutate(count = replace_na(count, 0)) %>%
  group_by(year, invert_species) %>%
  summarise(mean_count = mean(count)) %>%
  mutate(se = sd(mean_count, na.rm=TRUE)/sqrt(length(mean_count))) %>%
  ggplot(mapping = aes(year, mean_count, fill = invert_species)) +
    geom_col(position = "dodge") +
  geom_errorbar(aes(ymin = mean_count - se, ymax = mean_count + se),
                width=.1, position = "dodge") +
  scale_fill_viridis_d()

```

```{r mean-snails-per-quadrat-faceted}

all_inverts_mdr %>%
  filter(invert_species %in% c("Litt_l",
                               "Litt_o",
                               "Litt_s",
                               "Litt_spp"),
         !(year == 2017),
         !is.na(tide_ht)) %>%
  mutate(count = replace_na(count, 0)) %>%
  group_by(year, tide_ht, invert_species) %>%
  summarise(mean_count = mean(count)) %>%
  ggplot(mapping = aes(year, mean_count, fill = invert_species)) +
    geom_col(position = "dodge") +
  scale_fill_viridis_d() +
  facet_wrap("tide_ht", nrow = 1)

```

```{r mean-snails-per-quadrat-faceted-plus-L_vincta}

# reorder this so colors of Littorina are the same and L. vincta is last (is there a way to do this without making it an ordered factor?)
# how many years has L. vincta been on the survey? would they have counted it? ask Tanya

all_inverts_mdr %>%
  filter(invert_species %in% c("Litt_l",
                               "Litt_o",
                               "Litt_s",
                               "Litt_spp",
                               "Lacu_v"),
         !(year == 2017),
         !is.na(tide_ht)) %>%
  mutate(count = replace_na(count, 0)) %>%
  group_by(year, tide_ht, invert_species) %>%
  summarise(mean_count = mean(count)) %>%
  ggplot(mapping = aes(year, mean_count, fill = invert_species)) +
    geom_col(position = "dodge") +
  scale_fill_viridis_d() +
  facet_wrap("tide_ht", nrow = 1)

```