---
title: "MDR graphs"
author: "Kalimari"
output: github_document
---

```{r load-packages, message = FALSE}
library(tidyverse)
library(broom)
library(ggplot2)
library(readxl)
library(scales)
library(lubridate)
library(dplyr)
library(ggtext)
library(gganimate)
library(ggpattern)

se <- function(x) sd(x)/sqrt(length(x))
```

```{r load-data}
expanded_inverts_mdr <- read_csv("/cloud/project/analysis/expanded_inverts_mdr.csv")
expanded_seaweeds_mdr <- read_csv("/cloud/project/analysis/expanded_seaweeds_mdr.csv")
mdr_temp_allyears <- read_csv("/cloud/project/analysis/mdr_temp_allyears.csv")
all_tide_time <- read_csv("/cloud/project/analysis/all_tide_time.csv")
```

```{r total-snails-per-quadrat-unfaceted}

expanded_inverts_mdr %>%
  filter(invert_species %in% c("Litt_l",
                               "Litt_o",
                               "Litt_s"),
         !(year == 2017)) %>%
  ggplot(mapping = aes(year, count, fill = invert_species)) +
    geom_col(position = "dodge") +
  labs(fill = "snail species") +
  scale_fill_viridis_d(
    labels = c("Litt_l" = "Littorina littorea",
               "Litt_o" = "Littorina obtusata",
               "Litt_s" = "Littorina saxatilis")
  )

```

```{r total-snails-per-quadrat-faceted}

expanded_inverts_mdr %>%
  filter(invert_species %in% c("Litt_l",
                               "Litt_o",
                               "Litt_s"),
         !(year == 2017),
         !is.na(tide_ht)) %>%
  mutate(tide_ht = fct_relevel(tide_ht, c("H", "M", "L"))) %>%
  ggplot(mapping = aes(year, count, fill = invert_species)) +
    geom_col(position = "dodge") +
  labs(fill = "snail species") +
  scale_fill_viridis_d(
    labels = c("Litt_l" = "Littorina littorea",
               "Litt_o" = "Littorina obtusata",
               "Litt_s" = "Littorina saxatilis")
  ) +
  facet_wrap("tide_ht", nrow = 1)

# omitted 2017 and 2018 for all snail graphs (2017 includes L_spp, so not useful for these graphs, and 2018 is too messy)

```

```{r mean-snails-per-quadrat-unfaceted}

expanded_inverts_mdr %>%
  filter(invert_species %in% c("Litt_l",
                               "Litt_o",
                               "Litt_s"),
         !(year == 2017),
         !is.na(tide_ht)) %>%
  group_by(year, invert_species) %>%
  summarise(mean_count = mean(count), sd = sd(count), n = n()) %>%
  mutate(se = sd/sqrt(n)) %>%
  ggplot(mapping = aes(year, mean_count, fill = invert_species)) +
    geom_col(position = "dodge") +
  geom_errorbar(aes(ymin = mean_count - se, ymax = mean_count + se),
                width=.5, position = position_dodge(.9)) +
  labs(fill = "snail species") +
  scale_fill_viridis_d(
    labels = c("Litt_l" = "Littorina littorea",
               "Litt_o" = "Littorina obtusata",
               "Litt_s" = "Littorina saxatilis")
  )

# are the error bars doing what they're supposed to now?

```

```{r mean-snails-per-quadrat-faceted}

expanded_inverts_mdr %>%
  filter(invert_species %in% c("Litt_l",
                               "Litt_o",
                               "Litt_s"),
         !(year == 2017),
         !is.na(tide_ht)) %>%
  mutate(tide_ht = fct_relevel(tide_ht, c("H", "M", "L"))) %>%
  group_by(year, tide_ht, invert_species) %>%
  summarise(mean_count = mean(count), sd = sd(count), n = n()) %>%
  mutate(se = sd/sqrt(n)) %>%
  ggplot(mapping = aes(year, mean_count, fill = invert_species)) +
    geom_col(position = "dodge") +
  geom_errorbar(aes(ymin = mean_count - se, ymax = mean_count + se),
                width=.3, position = position_dodge(.9)) +
  labs(fill = "snail species") +
  scale_fill_viridis_d(
    labels = c("Litt_l" = "Littorina littorea",
               "Litt_o" = "Littorina obtusata",
               "Litt_s" = "Littorina saxatilis")
    ) +
  facet_wrap("tide_ht", nrow = 1)

# better to have all in same column or all in same row? if in same row, how to make them shorter?
# are these error bars right? they're better...

```

```{r mean-snails-per-quadrat-faceted-plus-Lacu_v-Nuce_l, fig.height = 4, fig.width = 9, fig.alt = "Bar plot of the mean number of snails per quadrat by year (2019-2023), tide height, and species, with the following trends: Lacuna vincta is only present at the low-tide level, starting at <1 per quadrat in 2022, and increasing to over 10 per quadrat in 2023. Littorina littorea is only present in 2019 and 2020 at high- and mid-tide levels (in all cases <5 per quadrat). Littorina obtusata is most abundant at the mid-tide level, increasing from about 8 per quadrat in 2019 to about 34 per quadrat in 2023, with a low point in 2021 of about 4 per quadrat. Littorina saxatilis is most abundant at the high-tide level, increasing from about 0 per quadrat in 2019 to about 15 per quadrat in 2022, dropping to about 10 per quadrat in 2023. Nucella lapillus is most abundant at the mid- and low-tide levels, increasing from about 0 per quadrat in 2019 to about 9 per quadrat at the mid-tide level and 19 per quadrat at the low-tide level in 2022, dropping to <3 per quadrat at both levels in 2023. Error bars represent +/- 1 standard error; there is minor overlap between some years for each species."}

# use this one for presentation
# include caption that says error bars represent +/- 1 standard error
# explain why we dropped 2017 and 2018 (2017 included counts of Littorina spp., and 2018 was too messy)
# how many years has L. vincta been on the survey? would they have counted it? ask Tanya

expanded_inverts_mdr %>%
  filter(invert_species %in% c("Litt_l",
                               "Litt_o",
                               "Litt_s",
                               "Lacu_v",
                               "Nuce_l"),
         !(year == 2017),
         !is.na(tide_ht)) %>%
  mutate(count = replace_na(count, 0)) %>%
  mutate(tide_ht_2 = case_when(tide_ht == "H" ~ "High Tide",
                               tide_ht == "M" ~ "Mid Tide",
                               tide_ht == "L" ~ "Low Tide")) %>%
  group_by(year, tide_ht_2, invert_species) %>%
  summarise(mean_count = mean(count), se_count = se(count)) %>%
  mutate(tide_ht_2 = as.factor(tide_ht_2)) %>%
  mutate(tide_ht_2 = fct_relevel(tide_ht_2, c("High Tide",
                                              "Mid Tide",
                                              "Low Tide"))) %>%
  ggplot(mapping = aes(year, mean_count, fill = invert_species)) +
    geom_col(position = "dodge", width = 0.7, size = .3) +
  labs(fill = "snail species") +
  geom_errorbar(aes(ymin = mean_count - se_count, ymax = mean_count + se_count),
                width=.3, position = position_dodge(0.7)) +
  scale_fill_viridis_d(labels = c("Litt_l" = "Littorina littorea",
                               "Litt_o" = "Littorina obtusata",
                               "Litt_s" = "Littorina saxatilis",
                               "Lacu_v" = "Lacuna vincta",
                               "Nuce_l" = "Nucella lapillus")) +
  facet_wrap("tide_ht_2", nrow = 1) +
  labs(x = "Year",
       y = "Mean Number of Snails Per Quadrat",
       title  = "Snail Abundance in the Mount Desert Rock Intertidal",
       subtitle = "by Year, Tide Height, and Species",
       fill = "Snail Species") +
  theme(legend.text = element_text(face="italic")) +
  theme(axis.title.y = element_text(margin = margin(t = 0, r = 8, b = 0, l = 0))) +
  theme(axis.title.x = element_text(margin = margin(t = 8, r = 0, b = 0, l = 0)))

```

```{r L-mean-seaweed-cover-graph}
expanded_seaweeds_mdr <- expanded_seaweeds_mdr %>%
  mutate(seaweed_simple = gsub("CC", "", seaweed_species)) %>%
  mutate(seaweed_simple = gsub("SC", "", seaweed_simple))
  # mutate(seaweed_simple = gsub("Fucu_d", "Fucu_spp", seaweed_simple)) %>%
  # mutate(seaweed_simple = gsub("Fucu_s", "Fucu_spp", seaweed_simple)) %>%
  # mutate(seaweed_simple = gsub("Fucu_v", "Fucu_spp", seaweed_simple))

expanded_seaweeds_mdr %>%
  filter(seaweed_simple %in% c("Fucu_spp",
                               "Fucu_d",
                               "Fucu_s",
                               "Fucu_v",
                               "Ulva_l",
                               # "Cera_r",
                               "Mast_s",
                               "Cora_o",
                               "Chon_c"),
         tide_ht == "L") %>%
  group_by(year, tide_ht, seaweed_simple) %>%
  summarise(mean_proportion = mean(proportion), sd = sd(proportion), n = n()) %>%
  mutate(se = sd/sqrt(n)) %>%
  mutate(ymin_seaweeds = mean_proportion - se) %>%
  mutate(ymin_seaweeds = case_when(ymin_seaweeds < 0 ~ 0,
                          TRUE ~ ymin_seaweeds)) %>%
  mutate(ymax_seaweeds = mean_proportion + se) %>%
  ggplot(mapping = aes(year, mean_proportion, fill = seaweed_simple)) +
    geom_col(position = "dodge") +
    labs(fill = "seaweed species") +
    scale_fill_viridis_d(labels = c("Chon_c" = "Chondrus crispus",
                                    "Cora_o" = "Corallina officinalis",
                                    "Fucu_d" = "Fucus distichus",
                                    "Fucu_s" = "Fucus spiralis",
                                    "Fucu_spp" = "Fucus spp.",
                                    "Fucu_v" = "Fucus vesiculosis",
                                    "Mast_s" = "Mastrocarpus stellatus",
                                    "Ulva_l" = "Ulva lactuca")) +
    scale_x_continuous(breaks = breaks_width(1)) +
    geom_errorbar(aes(ymin = ymin_seaweeds, ymax = ymax_seaweeds), width=.3, position = position_dodge(.9))

# sum ALL Fucus in each plot before calculating mean (I think I did this but not sure)
# a thought: where do the snails go at high tide? does it make sense to focus only on low if they go higher when tide is high?
```

```{r L-mean-seaweed-cover-graph-faceted, fig.height = 4, fig.width = 9, fig.alt = "Bar plots of the mean proportion of seaweed cover per quadrat by year (2017-2023) and seaweed color (brown, red, or green), faceted by species, with the following trends: Ascophyllum nodosum (brown) starts around 0.1 in 2017, increasing to 0.2 in 2019, and then decreasing to 0.1 by 2023. Chondrus crispus (red) starts around 0.15 in 2017, decreasing to 0.05 in 2019 and remaining around that level until 2023. Corallina officinalis (red) starts around 0.2 in 2017, decreasing to nearly 0 in 2019 with an increase to around 0.1 by 2023. Fucus spp. (brown) starts around 0.35 in 2017, decreasing to around 0.25 in 2019 and 2020, and dropping to 0.1 for 2021-2023. Mastocarpus stellatus (red) starts around 0.1 in 2017, increasing to 0.25 by 2020 and decreasing back to around 0.1 by 2023. Ulva lactuca (green) starts around 0.15 in 2017 and decreases to nearly 0 by 2023. For all species, 2018 was not included due to a lack of data. Error bars represent +/- 1 standard error; there is minor overlap between some years for each species."}

# use this one for presentation
# explain gap for 2018
# include caption that says error bars represent +/- 1 standard error

expanded_seaweeds_mdr <- expanded_seaweeds_mdr %>%
  mutate(seaweed_simple = case_when(grepl("Fucu", seaweed_species) ~ "Fucu_spp",
                                    TRUE ~ seaweed_species)) %>%
  mutate(seaweed_simple = gsub("CC", "", seaweed_simple)) %>%
  mutate(seaweed_simple = gsub("SC", "", seaweed_simple)) %>%
  mutate(proportion_new = case_when(seaweed_simple == "Ulva_l" & tide_ht == "H" ~ 0,
                                    TRUE ~ proportion))

seaweed_labs <- c("<i>Ascophyllum nodosum</i>",
                  "<i>Chondrus crispus</i>",
                  "<i>Corallina officinalis</i>",
                  "<i>Fucus</i> spp.",
                  "<i>Mastocarpus stellatus</i>",
                  "<i>Ulva lactuca</i>")

names(seaweed_labs) <- c("Asco_n",
                         "Chon_c",
                         "Cora_o",
                         "Fucu_spp",
                         "Mast_s",
                         "Ulva_l")

expanded_seaweeds_mdr %>%
  filter(seaweed_simple %in% names(seaweed_labs)) %>%
  group_by(year, tide_ht, quadrat_m, seaweed_simple) %>%
  summarise(sum_proportion = sum(proportion_new)) %>%
  filter(!is.na(quadrat_m)) %>%
  group_by(year, seaweed_simple) %>%
  summarise(mean_proportion = mean(sum_proportion),
            se_proportion = se(sum_proportion)) %>%
  mutate(ymin_seaweeds = mean_proportion - se_proportion) %>%
  mutate(ymin_seaweeds = case_when(ymin_seaweeds < 0 ~ 0,
                          TRUE ~ ymin_seaweeds)) %>%
  mutate(ymax_seaweeds = mean_proportion + se_proportion) %>% 
  mutate(seaweed_color = case_when(seaweed_simple %in% c("Asco_n",
                                                         "Fucu_spp",
                                                         "Lami_spp")
                                                         ~ "Brown",
                                   seaweed_simple %in% c("Cera_r",
                                                         "Chon_c",
                                                         "Cora_o",
                                                         "Mast_s",
                                                         "Porp_sp",
                                                         "Vert_l")
                                                         ~ "Red",
                                   seaweed_simple %in% c("Ulva_i",
                                                         "Ulva_l")
                                                         ~ "Green",
                                   TRUE ~ "Black")) %>%
  mutate(seaweed_color = as.factor(seaweed_color)) %>%
  mutate(seaweed_color = fct_relevel(seaweed_color, c("Brown", "Red", "Green"))) %>%
  ggplot(mapping = aes(year, mean_proportion, fill = seaweed_color)) +
  geom_col(position = "dodge") +
  scale_x_continuous(breaks = breaks_width(1)) +
  geom_errorbar(aes(ymin = ymin_seaweeds, ymax = ymax_seaweeds),
                  width=.3, position = position_dodge(.9)) +
  scale_fill_manual(values = c("Brown" = "#614428",
                               "Red" = "#CF594C",
                               "Green" = "#ABDD8A")) +
  facet_wrap(. ~seaweed_simple, labeller = labeller(seaweed_simple = seaweed_labs)) +
  theme(axis.text.x = element_text(size = 7)) +
  labs(x = "Year",
       y = "Mean Proportion of Seaweed per Quadrat",
       title = "Seaweed Cover in the Mount Desert Rock Intertidal",
       subtitle = "by Year and Species",
       fill = "Seaweed Color") +
  theme(axis.title.y = element_text(margin = margin(t = 0, r = 8, b = 0, l = 0))) +
  theme(axis.title.x = element_text(margin = margin(t = 8, r = 0, b = 0, l = 0))) +
  theme(strip.text = element_markdown())
```

```{r L-total-seaweed-cover-graph}
expanded_seaweeds_mdr %>%
  filter(seaweed_simple %in% c("Fucu_spp",
                               "Fucu_d",
                               "Fucu_s",
                               "Fucu_v",
                               "Ulva_l",
                               "Mast_s",
                               "Cora_o",
                               "Chon_c"),
         tide_ht == "L") %>%
  group_by(year, tide_ht, seaweed_simple) %>%
  ggplot(mapping = aes(year, proportion, fill = seaweed_simple)) +
    geom_col(position = "dodge") +
    labs(fill = "seaweed species") +
    scale_fill_viridis_d(labels = c("Cera_r" = "Ceramium rubrum",
                                    "Chon_c" = "Chondrus crispus",
                                    "Cora_o" = "Corallina officinalis",
                                    "Fucu_d" = "Fucus distichus",
                                    "Fucu_s" = "Fucus spiralis",
                                    "Fucu_spp" = "Fucus spp.",
                                    "Fucu_v" = "Fucus vesiculosis",
                                    "Mast_s" = "Mastrocarpus stellatus",
                                    "Ulva_l" = "Ulva lactuca")) +
    scale_x_continuous(breaks = breaks_width(1)) +
    coord_cartesian(ylim = c(0, NA))

# sum ALL Fucus in each plot before calculating mean (see previous code chunk)
# what's up with the error bars??
```

```{r total-ulva_l-graph}

expanded_seaweeds_mdr %>%
  filter(seaweed_simple == "Ulva_l",
         !is.na(tide_ht)) %>%
  group_by(year, tide_ht, seaweed_simple) %>%
  ggplot(mapping = aes(year, proportion_new, fill = tide_ht)) +
    geom_col() +
    labs(fill = "tide height") +
    scale_fill_viridis_d(labels = c("H" = "High",
                                    "L" = "Low",
                                    "M" = "Mid")) +
    scale_x_continuous(breaks = breaks_width(1)) +
    coord_cartesian(ylim = c(0, NA))

# I don't believe there was that much Ulva in the high quadrats
# ^fixed by removing all observations of Ulva in high quadrats (see seaweed graph codeblock above)

```


```{r temperature-graph-all-days, fig.alt = "Scatterplot of Mount Desert Rock mid tide temperatures in degrees Celsius, shown across a date range from 2017 to 2022. The temperatures range from negative 10 to positive 30 degrees Celsius and fluctuate throughout the year. Colder temperatures occur in the winter and warmer temperatures occur in the summer months."}

mdr_temp_allyears %>%
  group_by(date) %>%
  summarise(mean_temp_C_date = mean(temp_C, na.rm = TRUE)) %>%
  ggplot(mapping = aes(date, mean_temp_C_date)) +
  geom_point() +
  labs(y = "mean temperature (C)") +
  geom_abline(slope = 0, intercept = 0, color = "blue") +
  scale_x_date(breaks = breaks_width("1 year"))

mdr_temp_allyears %>%
  ggplot(mapping = aes(date, temp_C)) +
  geom_point(alpha = .1) +
  # geom_smooth() +
  labs(title = "Mid tide temperature at Mount Desert Rock ",
       subtitle = "From 2017 to 2022",
       y = "temperature (C)") +
  geom_abline(slope = 0, intercept = 0, color = "blue") +
  scale_x_date(breaks = breaks_width("1 year"))

```

```{r temp-graphs-by-tide, eval = FALSE}
mdr_temp_alltides %>%
  ggplot(mapping = aes(x = date.x, y = temp_C, colour = tide_ht)) +
  geom_point(alpha = .1) +
  # geom_smooth() +
  labs(y = "temperature (C)") +
  geom_abline(slope = 0, intercept = 0, color = "blue") +
  scale_x_date(breaks = breaks_width("1 year"))

mdr_temp_high_tide %>%
  ggplot(mapping = aes(date.x, temp_C)) +
  geom_point() +
  labs(y = "temperature (C)") +
  geom_abline(slope = 0, intercept = 0, color = "blue") +
  scale_x_date(breaks = breaks_width("1 year"))

mdr_temp_low_tide %>%
  ggplot(mapping = aes(date.x, temp_C)) +
  geom_point() +
  labs(y = "temperature (C)") +
  geom_abline(slope = 0, intercept = 0, color = "blue") +
  scale_x_date(breaks = breaks_width("1 year"))
```


```{r dominant-snails-species-animation, fig.alt = "Animation of the predominant snail species within each quadrat, categorized by tide height and depicting a change across the years 2019 to 2023. Starting in 2019, Littorina obtusata was the most abundant in the majority of quadrats at all tide heights. Then, it gradually declined over a two year period with Nucella lapillus taking the lead. In 2022, both species exhibited a balanced number of quadrats, and in 2023, Littorina obtusata held a significant majority of quadrats, all of which resided at the mid tide height while Nucella Lapillus held only 2 quadrats, both at the low tide height.Littorina littorea maintained a low number of quadrats (2-5) in which it was most abundant at the mid and high tide height. Starting in 2021, it did not hold any quadrats. Littorina saxatillis consistently had at least one quadrat in which it was the most abundant (with the exception of 2020) and stayed relatively consistent through the years with a range of 4-6 quadrats, all of which were at high tide height. Some quadrats had multiple species as the most abundant species, both these instances follow the trends described above. Quadrats in which no snail species were found held a range of 2-11, with the majority of quadrats falling into the high tide height. At mid tide height, only one quadrat was observed with no snail species."}

max_snail_species <- all_inverts_mdr %>%
  filter(invert_species %in% c("Lacu_v", 
                               "Litt_l", 
                               "Litt_o", 
                               "Litt_s", 
                               "Nuce_l"),
         !is.na(tide_ht),
         year != 2017) %>%
  group_by(year, quadrat_number, tide_ht) %>%
  slice_max(count, n = 1) %>%
  mutate(snail_species_max = ifelse(count == 0, NA, invert_species)) %>%
  distinct(snail_species_max, .keep_all = TRUE) %>%
  summarise(common_species = str_flatten(snail_species_max, collapse = ", "))

max_snail_per_quadrat <- max_snail_species %>%
  ggplot(aes(x = quadrat_number, 
             y = .25,
             fill = common_species,
             groups = year)) + 
  geom_tile(color = "white", linewidth = 2) +
  facet_wrap(~ tide_ht, strip.position = "left", ncol = 1) +
  scale_x_continuous(breaks = seq(1, 10, by = 1)) +
  theme(strip.text.y.left = element_text(angle=0),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank()) + 
  labs(title = "The Predominant Snail Species within each Quadrat by Tide Height",
       subtitle = "Year - {closest_state}",
       fill = "Snail Species") +
  xlab("Quadrat Number") +
  ylab("Tide Height") +
  scale_fill_manual(values = c("#440154FF",
                               "#414487FF",
                               "#2A788EFF",
                               "#7AD151FF",
                               "#FDE725FF",
                               "#7A52A9",
                               "#20A3879F",
                               "#D7BFDC",
                               "grey70"), 
                    breaks = c("Lacu_v",
                               "Litt_l",
                               "Litt_o",
                               "Litt_s",
                               "Nuce_l",
                               "Litt_l, Litt_o",
                               "Litt_o, Litt_s",
                               "Nuce_l, Litt_o, Lacu_v",
                               NA),
                    labels = c(expression(italic("Lacuna vincta")),
                               expression(italic("Littorina littorea")),
                               expression(italic("Littorina obtusata")),
                               expression(italic("Littorina saxatilis")),
                               expression(italic("Nucella lapillus")),
                               expression(italic("Littorina littorea, Littorina obtusata")),
                               expression(italic("Littorina obtusata, Littorina saxtilis")),
                               expression(italic("Lacuna vincta, Littorina obtusata, Nucella lapillus")),
                               "NA")) +
  transition_states(states = year,
                    transition_length = 3,
                    state_length = 3,
                    wrap = TRUE)

animate(max_snail_per_quadrat, duration = 10, height = 250, width = 775,  renderer=gifski_renderer(loop = TRUE))
anim_save()

```


```{r attempt-at-patterns} 

m <- max_snail_species %>%
  ggplot(aes(x = quadrat_number,
             y = 1, 
             group = year,
             fill = common_species,
             pattern = common_species)) +
  geom_tile_pattern(stat = "identity") +
  scale_fill_manual(name = "fill", 
                    values = c("Lacu_v" = "#440154FF",
                               "Litt_l" = "#414487FF",
                               "Litt_o" = "#2A788EFF",
                               "Litt_s" = "#7AD151FF",
                               "Nuce_l" = "#FDE725FF",
                               "Litt_l, Litt_o" = "white",
                               "Litt_s, Litt_o" = "white",
                               "Nuce_l, Litt_o, Lacu_v" = "white",
                               na.value = "grey70")) +
  scale_pattern_manual(name = "pattern", 
                       values = c("Lacu_v" = "none",
                                  "Litt_l" = "none",
                                  "Litt_o" = "none",
                                  "Litt_s" = "none",
                                  "Nuce_l" = "none",
                                  "Litt_l, Litt_o" = "circle",
                                  "Litt_o, Litt_s" = "circle",
                                  "Nuce_l, Litt_o, Lacu_v" = "circle",
                                  na.value = "none")) + 
  facet_wrap(~ tide_ht, strip.position = "left", ncol = 1)

# ERROR: Caused by error in `if (pat == "regular_polygon" && is.numeric(params$pattern_shape)) 

scale_pattern_discrete()
scale_tile_pattern()

```

